# <span style="color:red">Numpy Overview</span>

- Numerical Python 
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준


- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함 (map 등)
- 선형대수와 관련된 다양한 기능을 제공함
- C, C++, Fortran 등의 언어와 통합 가능
---

# <span style="color:red">Ndarray</span>
## Array Creation

In [9]:
#import antigravity
import numpy as np

test_array = np.array([1,4,5,8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

- numpy는 np.array 함수를 활용하여 배열을 생성함 -> ndarray
- numpy는 **하나의 데이터 type**만 배열에 넣을 수 있음
- List와 가장 큰 차이점, **Dynamic typing not supported** (빠른 속도 유지 위해)
- C의 Array를 사용하여 배열을 생성함

In [37]:
test_array_2 = np.array(['1','4',5,8], float)
type(test_array_2[1])

numpy.float64

---



## Numpy Array와 Python List의 특징 및 차이점

| <center>Numpy Array | <center>Python List |
| :---------: | :---------: |
| <center>데이터가 연속적으로 메모리 영역을 차지한다.                      | <center>해당 값의 주소값을 저장한다. |
| <center>정해진 공간을 할당해서 사용하기 때문에 여러 type을 담을 수 없다. | <center>for문을 사용하여 탐색할 경우 주소값의 위치를 찾아야 해서 시간이 오래 걸린다.|
    
---



## Array Shape

In [38]:
test_array.shape # Array(배열) 의 shape을 반환함

(4,)

(4, ) : 1차원에 4개의 element가 있는 벡터


In [39]:
matrix = [ [1,2,5,8],[1,2,5,8],[1,2,5,8] ]
np.array(matrix, int).shape

(3, 4)

In [40]:
tensor = [
          [ [1,2,5,8], [1,2,5,8], [1,2,5,8] ],
          [ [1,2,5,8], [1,2,5,8], [1,2,5,8] ],
          [ [1,2,5,8], [1,2,5,8], [1,2,5,8] ],
          [ [1,2,5,8], [1,2,5,8], [1,2,5,8] ]
         ]
np.array(tensor, int).shape

(4, 3, 4)


## Array Shape - ndim & size
- ndim: number of dimension
- size: data의 개수

In [41]:
np.array(tensor, int).ndim

3

In [42]:
np.array(tensor,int).size

48

---

## Array dtype
- ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory의 크기가 결정됨


- 자신이 사용하는 데이터의 타입에 맞추어 dtype를 설정해주면 <br/>불필요한 메모리 낭비를 줄일 수 있다.

In [43]:
np.array([[1, 2, 3],[4.5, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

- nbytes: ndarray object의 메모리 크기를 반환함

In [45]:
# 32bit(4byte)를 사용하는데 6개의 데이터가 있기 때문에
# 6*4 = 24byte를 사용하게 된다.
# 큰 데이터를 다룰 때 신경써야 함.
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32).nbytes

24

---
# <span style="color:red">Handling shape</span>
## Reshape **
- Array의 shape 크기를 변경함 (element의 개수는 동일)

In [47]:
test_matrix = [ [1,2,3,4], [5,6,7,8] ]
np.array(test_matrix).shape

(2, 4)

In [49]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
np.array(test_matrix).reshape(8,).shape

(8,)

- Array의 size만 같다면 다차원으로 자유롭게 변경 가능

In [52]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [57]:
np.array(test_matrix).reshape(-1,2).shape
# -1 : size를 기반으로 row 개수 선정 (col이 2니깐 알아서 row 갯수를 맞춰라)

(4, 2)

In [55]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

---
## Flatten
- 다차원 array를 1차원 array로 변환

In [58]:
test_matrix = [ [ [1,2,3,4], [1,2,5,8] ], 
                [ [1,2,3,4], [1,2,5,8] ] ] 
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

---
# <span style="color:red">Indexing & Slicing </span>
## Indexing

In [59]:
a = np.array([[1,2,3], [4.5,5,6]], int)
print(a)
print(a[0,0])  # Two-dimensional array representation-1
print(a[0][0]) # Two-dimensional array representation-2

[[1 2 3]
 [4 5 6]]
1
1


In [60]:
a[0,0] = 12 # Matrix 0,0에 12 할당
print(a)

a[0][0] = 5
print(a)

[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


- List와 달리 이차원 배열에서 [0,0]과 같은 표기법을 제공함
- Matrix일 경우 앞은 row, 뒤는 column을 의미함

---
## Slicing

In [68]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
a[:, 2:]   # 전체 row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [66]:
a[1, 1:3]  # 1 row의 1열~2열

array([7, 8])

In [69]:
a[1:3]     # 1 row ~ 2 row의 전체

array([[ 6,  7,  8,  9, 10]])

- List와 달리 행과 열 부분을 나눠서 slicing이 가능함
- Matrix의 부분집합을 추출할 때 유용함

In [70]:
b = np.array([ [0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14] ], int)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
b[:, ::2] # 전체를 탐색하되, 한 칸씩 건너뛴다.

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

---
# <span style="color:red">Creation functions</span>
## Arange **
- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [73]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [80]:
np.arange(0, 5, 0.5) # (시작, 끝, step)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [82]:
np.arange(0, 5, 0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [77]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

---
## Ones, Zeros and Empty
- zeros: 0으로 가득 찬 ndarray 생성

In [83]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [84]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- ones: 1로 가득찬 ndarray 생성

In [85]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [86]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- empty: shape만 주어지고 비어있는 ndarray 생성 <br/>
(memory initialization이 되지 않음)


In [114]:
np.empty(shape(10,), dtype=np.int8)

array(1, dtype=int8)

In [136]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Something_like
- ndarray의 shape 크기만큼 1, 0 또는 empty array를 반환

In [100]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

---
## Identity
- 단위 행렬(i 행렬)을 생성함

In [137]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [138]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Eye
- 대각선이 1인 행렬, k값의 시작 index 변경이 가능

In [139]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [140]:
np.eye(3) # identity와 동일

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
np.eye(3, 5, k=2) # k == start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Diag
- 대각 행렬의 값을 추출함

In [144]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [146]:
np.diag(matrix, k=1) # k == start index

array([1, 5])

## Random sampling

In [153]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포 (최솟값, 최댓값, 갯수)

array([[0.68483275, 0.22921014, 0.65567489, 0.75439027, 0.90821423],
       [0.51310083, 0.78056435, 0.33621439, 0.86169958, 0.27709743]])

In [155]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포 (평균, 정규분포, 갯수)

array([[ 1.11708099,  0.02134757, -0.00531061,  0.40087471,  0.56075541],
       [ 0.63589047,  0.57628128,  2.23745916,  0.64047846,  0.04726023]])

---
# <span style="color:red">Operation functions</span>
## Sum
- ndarray의 element간 합을 구함. List의 sum 기능과 동일

In [157]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [158]:
test_array.sum(dtype=np.float)

55.0

## Axis **
- 모든 operation function을 실행할 때, 기준이 되는 dimension 축

***새롭게 생긴 축이 axis = 0이 된다.***

**2차원 기준** <br/>
axis = 1은 row, 즉 벡터를 기준으로 함. (가장 처음 있는 축) <br/>
axis = 0은 col을 기준으로 함. (새롭게 생긴 축)

In [160]:
test_array = np.arange(1, 13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [164]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

 **3차원 기준** <br/>
axis = 2가 row를 기준으로 한다. <br/>
axis = 1은 col을 기준으로 한다. <br/>
axis = 0은 matrix가 여러 개 있는 축을 기준으로 한다. <br/>

In [165]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor
# (3, 3, 4) => (axis 0, axis 1, axis 2)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [166]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [167]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [168]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

---
## Mean & Std
- ndarray의 element 간 평균 또는 표준편차를 반환


In [170]:
test_array = np.arange(1, 13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [171]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [172]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

---
## Mathematical functions
> np.something 호출

1. exponential <br/>
: exp, expml, exp2, log, log10, log1p, log2, power, sqrt

2. trigonometric <br/>
: sin, cos, tan, acsin, arccos, atctan

3. hyperbolic <br/>
: sinh, cosh, tanh, acsinh, arccosh, atctanh

In [173]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

---
## Concatenate **
- Numpy array를 합치는 함수

In [175]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
a = np.array([ [1], [2], [3] ])
b = np.array([ [4], [5], [6] ])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

concatenate를 사용하여 vstack과 hstack을 한 번에 사용할 수 있다.

In [179]:
a = np.array([ [1,2,3] ])
b = np.array([ [4,5,6] ])
np.concatenate( (a,b), axis = 0 )

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
a = np.array([ [1,2], [3,4] ])
b = np.array([ [5,6] ])
np.concatenate( (a,b.T), axis=1 ) # b를 transpose 시킨다.

array([[1, 2, 5],
       [3, 4, 6]])

---
# <span style="color:red">Array operations</span>

## Operations b/t arrays
- Numpy는 array간 기본적인 사칙 연산을 지원함


In [183]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [184]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [185]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [186]:
test_a * test_a # element-wise operations

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

## Element-wise operations
- Array 간 shape이 같을 때 일어나는 연산

In [187]:
matrix_a = np.arange(1, 13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

## Dot product
- Matrix의 기본 연산
- dot 함수 사용

In [188]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [191]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [192]:
test_b.dot(test_a)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

## Transpose
- transpose 또는 T attribute 사용

In [194]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [197]:
test_a.T.dot(test_a) # (3x2) * (2x3)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

---

## Broadcasting **
- Shape이 다른 배열 간 연산을 지원하는 기능


- 덧셈(+), 뺄셈(-), 곱셈(*), 나눗셈(/), 몫(//), 제곱(*\*\*)도 가능 
- Scalar-vector 외에도 vector-matrix 간 연산도 지원

In [200]:
test_matrix = np.array( [[1,2,3], [4,5,6]], float)
scalar = 3

In [202]:
test_matrix + scalar # Matrix + Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [203]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10) # 10, 20, 30
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [204]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

---
## Numpy performance #1
- timeit: jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수

In [7]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*vector)
    return result

iteration_max = 1000 # 메모리가 딸려서 작은 수로 테스트함...

vector = list(range(iteration_max))
scalar = 2

In [8]:
# for loop을 이용한 성능
%timeit scalar_vector_product(scalar, vector) 

11 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
# list comprehension을 이용한 성능
%timeit [scalar*value for value in range(iteration_max)]

74.5 µs ± 4.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
# numpy를 이용한 성능
%timeit np.arange(iteration_max)*scalar

3 µs ± 94.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# <span style="color:red">Comparisions</span>

## All & Any
- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환 

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [12]:
np.any(a>5), np.any(a<0)

(True, False)

In [13]:
np.all(a>5), np.all(a<10)

(False, True)

---

## Comparison operation #1
- Numpy는 배열의 크기가 동일할 때 element 간 비교의 결과를 boolean type으로 반환하여 돌려줌

In [1]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [2]:
test_a == test_b

array([False, False, False])

In [3]:
(test_a > test_b).any()

True

---
## Comparison operation #2

In [5]:
a = np.array([1,3,0], float)
np.logical_and(a>0, a<3) # and 조건의 condition

array([ True, False, False])

In [6]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [8]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

---
## np.where **


In [10]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([3, 3, 2])

In [11]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

In [12]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [15]:
np.isfinite(a)

array([ True, False, False])

---
## argmax & argmin **
- array 내 최대값 또는 최소값의 index를 반환함

In [16]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

- axis 기반의 반환

In [17]:
a = np.array([ [1,2,4,7], [9,88,6,45], [9,76,3,4] ])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

# <span style="color:red">Boolean & Fancy index</span>

## Boolean index
- numpy에서 특정 조건에 따른 값을 배열 형태로 추출할 수 있음
- Comparison operation 함수들도 모두 사용 가능

In [18]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [19]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [20]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [22]:
A = np.array( [
    [12, 13, 14, 12, 16, 14, 11, 10, 9],
    [11, 14, 12, 15, 15, 16, 17, 10, 12],
    [9, 11, 16, 15, 14, 16, 10, 12, 12],
    [10, 16, 15, 17, 14, 18, 19, 19, 10],
    [10, 16, 15, 17, 14, 18, 19, 19, 10],
    [10, 16, 15, 17, 14, 18, 19, 19, 10],
    [10, 16, 15, 17, 14, 18, 19, 19, 10]
] )

B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1]])

---
## Fancy index
- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [23]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 반드시 integer로 선언
a[b] # braket index : b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [24]:
a.take(b) # take 함수 : braket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

Martix 형태의 데이터도 가능

In [25]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

# <span style="color:red">Data I/O</span>

## loadtxt & savetxt
- Text type의 데이터를 읽고, 저장하는 기능

In [ ]:
# 파일 호출
a = np.loadtxt("./populations.txt")
a[:10]

In [ ]:
# int type 변환
a_int = a.astype(int)
a_int[:3]

In [ ]:
# csv 파일로 저장
np.savetxt('int_data.csv', a_int, delimiter=",")

## numpy object - npy
- Numpy object(pickle) 형태로 데이터를 저장하고 불러옴
- Binary 파일 형태로 저장함

In [ ]:
np.save('npy_test', arr=a_int)

In [ ]:
npy_array = np.load(file='npy_test.npy')
npy_array[:3]